## Importing Libraries

In [1]:
import pandas as pd

## Import file

In [2]:
weather = pd.read_csv("climate_daily_Ottawa_Toronto_2020.csv")

## Get first 5 rows

In [3]:
weather.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-75.67,45.32,OTTAWA INTL A,6106001,2020-01-01,2020,1,1,NaN,1.1,...,0.0,T,0.0,T,15.0,NaN,26.0,NaN,35.0,NaN
1,-75.67,45.32,OTTAWA INTL A,6106001,2020-01-02,2020,1,2,NaN,4.4,...,0.0,NaN,0.0,NaN,15.0,NaN,20.0,NaN,41.0,NaN
2,-75.67,45.32,OTTAWA INTL A,6106001,2020-01-03,2020,1,3,NaN,4.7,...,0.0,NaN,0.0,NaN,6.0,NaN,NaN,NaN,NaN,M
3,-75.67,45.32,OTTAWA INTL A,6106001,2020-01-04,2020,1,4,NaN,1.4,...,1.8,NaN,1.3,NaN,4.0,NaN,NaN,NaN,NaN,M
4,-75.67,45.32,OTTAWA INTL A,6106001,2020-01-05,2020,1,5,NaN,-3.0,...,0.0,T,0.0,T,6.0,NaN,28.0,NaN,37.0,NaN

In [4]:
weather.tail()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
727,-79.4,43.67,TORONTO CITY,6158355,2020-12-27,2020,12,27,NaN,4.7,...,NaN,NaN,0.5,NaN,3.0,NaN,NaN,M,NaN,M
728,-79.4,43.67,TORONTO CITY,6158355,2020-12-28,2020,12,28,NaN,5.2,...,NaN,NaN,3.4,NaN,NaN,NaN,NaN,M,NaN,M
729,-79.4,43.67,TORONTO CITY,6158355,2020-12-29,2020,12,29,NaN,-0.5,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M
730,-79.4,43.67,TORONTO CITY,6158355,2020-12-30,2020,12,30,NaN,5.6,...,NaN,NaN,5.9,NaN,NaN,NaN,NaN,M,NaN,M
731,-79.4,43.67,TORONTO CITY,6158355,2020-12-31,2020,12,31,NaN,2.5,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M

## Get number of rows and number of columns

In [5]:
weather.shape

(732, 31)

## Delete columns from dataFrame that are not needed

In [6]:
weather = weather.drop(["Climate ID","Total Snow (cm)", "Total Snow Flag", "Snow on Grnd (cm)", "Dir of Max Gust (10s deg)", "Spd of Max Gust (km/h)", "Spd of Max Gust Flag"], axis=1)

weather = weather.drop(["Max Temp Flag","Heat Deg Days Flag", "Total Rain (mm)", "Total Rain Flag", "Total Precip Flag", "Snow on Grnd Flag"], axis=1)

weather = weather.drop(["Heat Deg Days (°C)","Cool Deg Days (°C)", "Cool Deg Days Flag", "Dir of Max Gust Flag", "Data Quality", "Mean Temp (°C)"], axis=1)

weather = weather.drop(["Min Temp Flag","Mean Temp Flag", "Longitude (x)", "Latitude (y)"], axis=1)

In [7]:
weather.head()

,Station Name,Date/Time,Year,Month,Day,Max Temp (°C),Min Temp (°C),Total Precip (mm)
0,OTTAWA INTL A,2020-01-01,2020,1,1,1.1,-2.0,0.0
1,OTTAWA INTL A,2020-01-02,2020,1,2,4.4,-4.6,0.0
2,OTTAWA INTL A,2020-01-03,2020,1,3,4.7,1.2,0.0
3,OTTAWA INTL A,2020-01-04,2020,1,4,1.4,-3.0,1.3
4,OTTAWA INTL A,2020-01-05,2020,1,5,-3.0,-12.9,0.0

## Keep dates from April to July only

In [8]:
invalidMonths = weather[ (weather['Month'] == 1) | (weather['Month'] == 2) | (weather['Month'] == 3) | (weather['Month'] == 8) | (weather['Month'] == 9) | (weather['Month'] == 10) | (weather['Month'] ==11)| (weather['Month'] ==12) ].index

# Delete these row indexes from dataFrame
weather.drop(invalidMonths , inplace=True)

In [9]:
weather.head()

,Station Name,Date/Time,Year,Month,Day,Max Temp (°C),Min Temp (°C),Total Precip (mm)
91,OTTAWA INTL A,2020-04-01,2020,4,1,7.4,-2.6,0.0
92,OTTAWA INTL A,2020-04-02,2020,4,2,10.8,-1.4,0.0
93,OTTAWA INTL A,2020-04-03,2020,4,3,10.0,3.7,1.5
94,OTTAWA INTL A,2020-04-04,2020,4,4,14.3,2.3,0.0
95,OTTAWA INTL A,2020-04-05,2020,4,5,10.4,-0.2,0.8

## Get number of rows and number of columns

In [10]:
weather.shape

(244, 8)

## Renaming columns to match DB

In [11]:
weather = weather.rename(columns = {"Station Name": "city", 
                                  "Max Temp (°C)":"temp_high", 
                                  "Min Temp (°C)": "temp_high",
                                    "Total Precip (mm)":"precipitation",
                                     })

weather.rename_axis("weather_id")

,city,Date/Time,Year,Month,Day,temp_high,temp_high,precipitation
weather_id,,,,,,,,
91,OTTAWA INTL A,2020-04-01,2020,4,1,7.4,-2.6,0.0
92,OTTAWA INTL A,2020-04-02,2020,4,2,10.8,-1.4,0.0
93,OTTAWA INTL A,2020-04-03,2020,4,3,10.0,3.7,1.5
94,OTTAWA INTL A,2020-04-04,2020,4,4,14.3,2.3,0.0
95,OTTAWA INTL A,2020-04-05,2020,4,5,10.4,-0.2,0.8
...,...,...,...,...,...,...,...,...
574,TORONTO CITY,2020-07-27,2020,7,27,33.2,22.8,2.7
575,TORONTO CITY,2020-07-28,2020,7,28,31.6,19.6,0.8
576,TORONTO CITY,2020-07-29,2020,7,29,29.7,19.4,1.9
577,TORONTO CITY,2020-07-30,2020,7,30,28.5,18.2,0.9
578,TORONTO CITY,2020-07-31,2020,7,31,28.6,19.8,1.0

## Save cleaned data to csv

In [12]:
weather.to_csv("weather_dimension.csv",index=True)